name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install and compile Dart Sass
        run: |
          curl -L https://github.com/sass/dart-sass/releases/latest/download/dart-sass-linux-x64.tar.gz | tar xz
          ./dart-sass/sass styles:styles

      - name: Copy site content to deploy folder
        run: |
          rm -rf out
          mkdir out
          cp -r html/* out/
          cp -r media out/
          cp