name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dart Sass
        run: npm install -g sass

      - name: Compile Sass to CSS
        run: sass styles/main.scss styles/main.css

      - name: Copy site content to deploy folder
        run: |
          rm -rf out
          mkdir out
          cp -r html/* out/
          cp -r media out/
          cp -r script out/
          cp -r styles out/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out